import { ReactComponent as Tire1 } from "assets/images/search/kh_hp71_d14.svg"
import { ReactComponent as Tire2 } from "assets/images/search/kh_hp71_d15.svg"
import { ReactComponent as Tire3 } from "assets/images/search/kh_hp71_d16.svg"

/* backend 연동 전 UX/UI 확인 및 코드 작성용 */

const Tires = [
    {
        id: 1,
        image: <Tire1/>,
        brand: "금호",
        name: "타이어",
        keyword1: "여름용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 2,
        image: <Tire1/>,
        brand: "넥센",
        name: "타이어드",
        keyword1: "사계절용", 
        keyword2: "승용차", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 3,
        image: <Tire1/>,
        brand: "한국",
        name: "넥타이",
        keyword1: "겨울용", 
        keyword2: "승용차", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 4,
        image: <Tire1/>,
        brand: "금호",
        name: "이름",
        keyword1: "여름용", 
        keyword2: "SUV", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 5,
        image: <Tire1/>,
        brand: "넥센",
        name: "타이어 이름 5",
        keyword1: "겨울용", 
        keyword2: "승용차", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 6,
        image: <Tire1/>,
        brand: "한국",
        name: "타이어 이름 6",
        keyword1: "삼계절용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 7,
        image: <Tire2/>,
        brand: "금호",
        name: "타이어 이름 7",
        keyword1: "삼계절용", 
        keyword2: "승용차", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 8,
        image: <Tire2/>,
        brand: "넥센",
        name: "타이어 이름 8",
        keyword1: "여름용", 
        keyword2: "SUV", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 9,
        image: <Tire2/>,
        brand: "한국",
        name: "타이어 이름 9",
        keyword1: "여름용", 
        keyword2: "승용차", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 10,
        image: <Tire2/>,
        brand: "금호",
        name: "타이어 이름 10",
        keyword1: "겨울용", 
        keyword2: "SUV", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 11,
        image: <Tire2/>,
        brand: "넥센",
        name: "타이어 이름 11",
        keyword1: "사계절용", 
        keyword2: "승용차", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 12,
        image: <Tire2/>,
        brand: "한국",
        name: "타이어 이름 12",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 13,
        image: <Tire3/>,
        brand: "금호",
        name: "타이어 이름 13",
        keyword1: "여름용", 
        keyword2: "승용차", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 14,
        image: <Tire3/>,
        brand: "넥센",
        name: "타이어 이름 14",
        keyword1: "여름용", 
        keyword2: "SUV", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 15,
        image: <Tire3/>,
        brand: "한국",
        name: "타이어 이름 15",
        keyword1: "겨울용", 
        keyword2: "승용차", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 16,
        image: <Tire3/>,
        brand: "금호",
        name: "타이어 이름 16",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "절약형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 17,
        image: <Tire3/>,
        brand: "넥센",
        name: "타이어 이름 17",
        keyword1: "사계절용", 
        keyword2: "승용차", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 18,
        image: <Tire3/>,
        brand: "한국",
        name: "타이어 이름 18",
        keyword1: "사계절용", 
        keyword2: "SUV", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 19,
        image: <Tire3/>,
        brand: "금호",
        name: "타이어 이름 19",
        keyword1: "겨울용", 
        keyword2: "승용차", 
        keyword3: "고급형", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
    {
        id: 20,
        image: <Tire3/>,
        brand: "한국",
        name: "타이어 이름 20",
        keyword1: "여름용", 
        keyword2: "SUV", 
        keyword3: "가심비", 
        keyword4: "연비짱",
        rate: "4.7",
        review: "(2,165)",
    },
]

export { Tires }